/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { CyberjusticeAPIsContext } from "./cyberjusticeAPIsContext";

class CyberjusticeAPIs extends CyberjusticeAPIsContext {
  // Operation groups
  async: operations.Async;
  businessInformation: operations.BusinessInformation;
  calendar: operations.Calendar;
  document: operations.Document;
  exchange: operations.Exchange;
  form: operations.Form;
  hearing: operations.Hearing;
  journal: operations.Journal;
  judicialEntity: operations.JudicialEntity;
  judicialFile: operations.JudicialFile;
  location: operations.Location;
  lookup: operations.Lookup;
  prosecutingAuthority: operations.ProsecutingAuthority;
  request: operations.Request;
  secureMail: operations.SecureMail;
  security: operations.Security;
  tag: operations.Tag;
  uProfile: operations.UProfile;
  user: operations.User;
  witness: operations.Witness;

  /**
   * Initializes a new instance of the CyberjusticeAPIs class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.CyberjusticeAPIsOptions) {
    super(options);
    this.async = new operations.Async(this);
    this.businessInformation = new operations.BusinessInformation(this);
    this.calendar = new operations.Calendar(this);
    this.document = new operations.Document(this);
    this.exchange = new operations.Exchange(this);
    this.form = new operations.Form(this);
    this.hearing = new operations.Hearing(this);
    this.journal = new operations.Journal(this);
    this.judicialEntity = new operations.JudicialEntity(this);
    this.judicialFile = new operations.JudicialFile(this);
    this.location = new operations.Location(this);
    this.lookup = new operations.Lookup(this);
    this.prosecutingAuthority = new operations.ProsecutingAuthority(this);
    this.request = new operations.Request(this);
    this.secureMail = new operations.SecureMail(this);
    this.security = new operations.Security(this);
    this.tag = new operations.Tag(this);
    this.uProfile = new operations.UProfile(this);
    this.user = new operations.User(this);
    this.witness = new operations.Witness(this);
  }
}

// Operation Specifications

export {
  CyberjusticeAPIs,
  CyberjusticeAPIsContext,
  Models as CyberjusticeAPIsModels,
  Mappers as CyberjusticeAPIsMappers
};
export * from "./operations";
