/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as tslib_1 from "tslib";
import * as msRest from "@azure/ms-rest-js";
var packageName = "";
var packageVersion = "";
var CyberjusticeAPIsContext = /** @class */ (function (_super) {
    tslib_1.__extends(CyberjusticeAPIsContext, _super);
    /**
     * Initializes a new instance of the CyberjusticeAPIsContext class.
     * @param [options] The parameter options
     */
    function CyberjusticeAPIsContext(options) {
        var _this = this;
        if (!options) {
            options = {};
        }
        if (!options.userAgent) {
            var defaultUserAgent = msRest.getDefaultUserAgentValue();
            options.userAgent = packageName + "/" + packageVersion + " " + defaultUserAgent;
        }
        _this = _super.call(this, undefined, options) || this;
        _this.baseUri = options.baseUri || _this.baseUri || "https://localhost:441";
        _this.requestContentType = "application/json; charset=utf-8";
        return _this;
    }
    return CyberjusticeAPIsContext;
}(msRest.ServiceClient));
export { CyberjusticeAPIsContext };
//# sourceMappingURL=cyberjusticeAPIsContext.js.map