/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/secureMailMappers";
import * as Parameters from "../models/parameters";
/** Class representing a SecureMail. */
var SecureMail = /** @class */ (function () {
    /**
     * Create a SecureMail.
     * @param {CyberjusticeAPIsContext} client Reference to the service client.
     */
    function SecureMail(client) {
        this.client = client;
    }
    SecureMail.prototype.getMailList = function (options, callback) {
        return this.client.sendOperationRequest({
            options: options
        }, getMailListOperationSpec, callback);
    };
    SecureMail.prototype.getMail = function (type, culture, options, callback) {
        return this.client.sendOperationRequest({
            type: type,
            culture: culture,
            options: options
        }, getMailOperationSpec, callback);
    };
    return SecureMail;
}());
export { SecureMail };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var getMailListOperationSpec = {
    httpMethod: "GET",
    path: "SecureMail/GET/MailList",
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelServiceContractsSecureMailEmailData"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
var getMailOperationSpec = {
    httpMethod: "GET",
    path: "SecureMail/GET/Mail",
    queryParameters: [
        Parameters.type,
        Parameters.culture
    ],
    responses: {
        200: {
            bodyMapper: Mappers.CyberjusticeLabKernelServiceContractsSecureMailEmailData
        },
        default: {}
    },
    serializer: serializer
};
//# sourceMappingURL=secureMail.js.map