/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/uProfileMappers";
import * as Parameters from "../models/parameters";
/** Class representing a UProfile. */
var UProfile = /** @class */ (function () {
    /**
     * Create a UProfile.
     * @param {CyberjusticeAPIsContext} client Reference to the service client.
     */
    function UProfile(client) {
        this.client = client;
    }
    UProfile.prototype.getCurrentUserProfile = function (options, callback) {
        return this.client.sendOperationRequest({
            options: options
        }, getCurrentUserProfileOperationSpec, callback);
    };
    UProfile.prototype.getUserProfile = function (fileId, username, realm, options, callback) {
        return this.client.sendOperationRequest({
            fileId: fileId,
            username: username,
            realm: realm,
            options: options
        }, getUserProfileOperationSpec, callback);
    };
    UProfile.prototype.getRealmUserProfiles = function (options, callback) {
        return this.client.sendOperationRequest({
            options: options
        }, getRealmUserProfilesOperationSpec, callback);
    };
    return UProfile;
}());
export { UProfile };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var getCurrentUserProfileOperationSpec = {
    httpMethod: "GET",
    path: "UProfile/GET/CurrentUserProfile",
    responses: {
        200: {
            bodyMapper: Mappers.CyberjusticeLabKernelServiceContractsUProfileUserData
        },
        default: {}
    },
    serializer: serializer
};
var getUserProfileOperationSpec = {
    httpMethod: "GET",
    path: "UProfile/GET/UserProfile",
    queryParameters: [
        Parameters.fileId0,
        Parameters.username,
        Parameters.realm
    ],
    responses: {
        200: {
            bodyMapper: Mappers.CyberjusticeLabKernelServiceContractsUProfileUserData
        },
        default: {}
    },
    serializer: serializer
};
var getRealmUserProfilesOperationSpec = {
    httpMethod: "GET",
    path: "UProfile/GET/RealmUserProfiles",
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelServiceContractsUProfileUserData"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
//# sourceMappingURL=uProfile.js.map