/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/userMappers";
/** Class representing a User. */
var User = /** @class */ (function () {
    /**
     * Create a User.
     * @param {CyberjusticeAPIsContext} client Reference to the service client.
     */
    function User(client) {
        this.client = client;
    }
    User.prototype.getCurrentRealmUsers = function (options, callback) {
        return this.client.sendOperationRequest({
            options: options
        }, getCurrentRealmUsersOperationSpec, callback);
    };
    User.prototype.getOrganizations = function (options, callback) {
        return this.client.sendOperationRequest({
            options: options
        }, getOrganizationsOperationSpec, callback);
    };
    User.prototype.getOrganizationsSummaries = function (options, callback) {
        return this.client.sendOperationRequest({
            options: options
        }, getOrganizationsSummariesOperationSpec, callback);
    };
    return User;
}());
export { User };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var getCurrentRealmUsersOperationSpec = {
    httpMethod: "GET",
    path: "User/GET/CurrentRealmUsers",
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelServiceContractsUserUserData"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
var getOrganizationsOperationSpec = {
    httpMethod: "GET",
    path: "User/GET/Organizations",
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelServiceContractsUserOrganizationData"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
var getOrganizationsSummariesOperationSpec = {
    httpMethod: "GET",
    path: "User/GET/OrganizationsSummaries",
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelSharedUserModelsOrganizationSummaryModel"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
//# sourceMappingURL=user.js.map