/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/businessInformationMappers";
import * as Parameters from "../models/parameters";
/** Class representing a BusinessInformation. */
var BusinessInformation = /** @class */ (function () {
    /**
     * Create a BusinessInformation.
     * @param {CyberjusticeAPIsContext} client Reference to the service client.
     */
    function BusinessInformation(client) {
        this.client = client;
    }
    BusinessInformation.prototype.validateTransitionStatus = function (statusTo, statusFrom, fileId, options, callback) {
        return this.client.sendOperationRequest({
            statusTo: statusTo,
            statusFrom: statusFrom,
            fileId: fileId,
            options: options
        }, validateTransitionStatusOperationSpec, callback);
    };
    BusinessInformation.prototype.judicialFileWithFormProposalsCount = function (judicialEntityId, businessRuleName, options, callback) {
        return this.client.sendOperationRequest({
            judicialEntityId: judicialEntityId,
            businessRuleName: businessRuleName,
            options: options
        }, judicialFileWithFormProposalsCountOperationSpec, callback);
    };
    return BusinessInformation;
}());
export { BusinessInformation };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var validateTransitionStatusOperationSpec = {
    httpMethod: "GET",
    path: "BusinessInformation/GET/ValidateTransitionStatus",
    queryParameters: [
        Parameters.statusTo,
        Parameters.statusFrom,
        Parameters.fileId0
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Object"
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
var judicialFileWithFormProposalsCountOperationSpec = {
    httpMethod: "GET",
    path: "BusinessInformation/GET/JudicialFileWithFormProposalsCount",
    queryParameters: [
        Parameters.judicialEntityId0,
        Parameters.businessRuleName
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelDataAccessBusinessInformationJudicialFileWithFormProposalsCount"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
//# sourceMappingURL=businessInformation.js.map