/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as tslib_1 from "tslib";
import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/exchangeMappers";
import * as Parameters from "../models/parameters";
/** Class representing a Exchange. */
var Exchange = /** @class */ (function () {
    /**
     * Create a Exchange.
     * @param {CyberjusticeAPIsContext} client Reference to the service client.
     */
    function Exchange(client) {
        this.client = client;
    }
    Exchange.prototype.getForumMessages = function (fileId, options, callback) {
        return this.client.sendOperationRequest({
            fileId: fileId,
            options: options
        }, getForumMessagesOperationSpec, callback);
    };
    Exchange.prototype.getForumMessages1 = function (requestModel, options, callback) {
        return this.client.sendOperationRequest({
            requestModel: requestModel,
            options: options
        }, getForumMessages1OperationSpec, callback);
    };
    Exchange.prototype.getForumMessage = function (fileId, forumId, options, callback) {
        return this.client.sendOperationRequest({
            fileId: fileId,
            forumId: forumId,
            options: options
        }, getForumMessageOperationSpec, callback);
    };
    Exchange.prototype.addForumMessage = function (forumMessageModel, options, callback) {
        return this.client.sendOperationRequest({
            forumMessageModel: forumMessageModel,
            options: options
        }, addForumMessageOperationSpec, callback);
    };
    Exchange.prototype.addPartyToForumMessages = function (partyForumMessageModel, options, callback) {
        return this.client.sendOperationRequest({
            partyForumMessageModel: partyForumMessageModel,
            options: options
        }, addPartyToForumMessagesOperationSpec, callback);
    };
    Exchange.prototype.addForumMessageAttributes = function (forumMessageAttributesModel, options, callback) {
        return this.client.sendOperationRequest({
            forumMessageAttributesModel: forumMessageAttributesModel,
            options: options
        }, addForumMessageAttributesOperationSpec, callback);
    };
    return Exchange;
}());
export { Exchange };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var getForumMessagesOperationSpec = {
    httpMethod: "GET",
    path: "Exchange/GET/ForumMessages",
    queryParameters: [
        Parameters.fileId0
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelServiceContractsExchangeForumData"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
var getForumMessages1OperationSpec = {
    httpMethod: "POST",
    path: "Exchange/POST/ForumMessages",
    requestBody: {
        parameterPath: "requestModel",
        mapper: tslib_1.__assign({}, Mappers.CyberjusticeLabKernelSharedExchangeModelsForumMessageApiRequestData, { required: true })
    },
    responses: {
        200: {
            bodyMapper: Mappers.CyberjusticeLabKernelSharedExchangeModelsForumMessageApiResponseData
        },
        default: {}
    },
    serializer: serializer
};
var getForumMessageOperationSpec = {
    httpMethod: "GET",
    path: "Exchange/GET/ForumMessage",
    queryParameters: [
        Parameters.fileId0,
        Parameters.forumId
    ],
    responses: {
        200: {
            bodyMapper: Mappers.CyberjusticeLabKernelServiceContractsExchangeForumData
        },
        default: {}
    },
    serializer: serializer
};
var addForumMessageOperationSpec = {
    httpMethod: "POST",
    path: "Exchange/POST/AddForumMessage",
    requestBody: {
        parameterPath: "forumMessageModel",
        mapper: tslib_1.__assign({}, Mappers.CyberjusticeLabKernelSharedExchangeModelsAddForumMessageModel, { required: true })
    },
    responses: {
        404: {},
        default: {}
    },
    serializer: serializer
};
var addPartyToForumMessagesOperationSpec = {
    httpMethod: "POST",
    path: "Exchange/POST/AddPartyToForumMessages",
    requestBody: {
        parameterPath: "partyForumMessageModel",
        mapper: tslib_1.__assign({}, Mappers.CyberjusticeLabKernelSharedExchangeModelsAddPartyToForumMessagesModel, { required: true })
    },
    responses: {
        404: {},
        default: {}
    },
    serializer: serializer
};
var addForumMessageAttributesOperationSpec = {
    httpMethod: "POST",
    path: "Exchange/POST/AddForumMessageAttributes",
    requestBody: {
        parameterPath: "forumMessageAttributesModel",
        mapper: tslib_1.__assign({}, Mappers.CyberjusticeLabKernelSharedExchangeModelsAddForumMessageAttributesModel, { required: true })
    },
    responses: {
        404: {},
        default: {}
    },
    serializer: serializer
};
//# sourceMappingURL=exchange.js.map