/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/hearingMappers";
import * as Parameters from "../models/parameters";
/** Class representing a Hearing. */
var Hearing = /** @class */ (function () {
    /**
     * Create a Hearing.
     * @param {CyberjusticeAPIsContext} client Reference to the service client.
     */
    function Hearing(client) {
        this.client = client;
    }
    Hearing.prototype.getMenuData = function (hearingId, menuId, options, callback) {
        return this.client.sendOperationRequest({
            hearingId: hearingId,
            menuId: menuId,
            options: options
        }, getMenuDataOperationSpec, callback);
    };
    Hearing.prototype.getAllJudgesMenuData = function (fileId, options, callback) {
        return this.client.sendOperationRequest({
            fileId: fileId,
            options: options
        }, getAllJudgesMenuDataOperationSpec, callback);
    };
    return Hearing;
}());
export { Hearing };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var getMenuDataOperationSpec = {
    httpMethod: "GET",
    path: "Hearing/GET/MenuData",
    queryParameters: [
        Parameters.hearingId,
        Parameters.menuId
    ],
    responses: {
        200: {
            bodyMapper: Mappers.CyberjusticeLabKernelServiceContractsHearingMenuData
        },
        default: {}
    },
    serializer: serializer
};
var getAllJudgesMenuDataOperationSpec = {
    httpMethod: "GET",
    path: "Hearing/GET/AllJudgesMenuData",
    queryParameters: [
        Parameters.fileId0
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "CyberjusticeLabKernelServiceContractsHearingMenuData"
                        }
                    }
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
//# sourceMappingURL=hearing.js.map