export default {
  fileIds: [],
  judicialFileIds: [],
  representativeIds: [],
  excludedFormCodes: [],
  includedFormIds: [],
  excludedStatuses: [],
  fileAttributesQuery: {},
  statuses: [],
  closingReasons: [],
  minCreatedDate: null,
  maxCreatedDate: null,
  searchStatuses: [],
  searchText: null,
  searchBy: [],
  searchActions: [],
  take: null,
  skip: null,
  OrderBy: null,
  OrderByDescending: false
};
