/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export { CyberjusticeLabKernelServiceContractsJudicialEntityJudicialEntityData, CyberjusticeLabKernelServiceContractsJudicialEntityNeutralPredicateData, CyberjusticeLabKernelServiceContractsJudicialEntityProsecutingAgentPredicateData } from "../models/mappers";
//# sourceMappingURL=judicialEntityMappers.js.map