/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export { CyberjusticeLabKernelSharedLocationLocationBuildingData, CyberjusticeLabKernelSharedLocationLocationRoomData, CyberjusticeLabKernelSharedLocationLocationBuildingUpdateData, CyberjusticeLabKernelSharedLocationLocationRoomUpdateData, CyberjusticeLabKernelSharedLocationLocationBuildingCreateData, CyberjusticeLabKernelSharedLocationLocationRoomCreateData } from "../models/mappers";
//# sourceMappingURL=locationMappers.js.map