/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
export var activeOnly = {
    parameterPath: [
        "options",
        "activeOnly"
    ],
    mapper: {
        serializedName: "activeOnly",
        type: {
            name: "Boolean"
        }
    }
};
export var aggregatorCode = {
    parameterPath: [
        "options",
        "aggregatorCode"
    ],
    mapper: {
        serializedName: "aggregatorCode",
        type: {
            name: "String"
        }
    }
};
export var aggregatorCodeIsSubstring0 = {
    parameterPath: "aggregatorCodeIsSubstring",
    mapper: {
        required: true,
        serializedName: "aggregatorCodeIsSubstring",
        type: {
            name: "Boolean"
        }
    }
};
export var aggregatorCodeIsSubstring1 = {
    parameterPath: [
        "options",
        "aggregatorCodeIsSubstring"
    ],
    mapper: {
        serializedName: "aggregatorCodeIsSubstring",
        type: {
            name: "Boolean"
        }
    }
};
export var aggregatorsCodes = {
    parameterPath: "aggregatorsCodes",
    mapper: {
        required: true,
        serializedName: "aggregatorsCodes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var baseCalendarId = {
    parameterPath: "baseCalendarId",
    mapper: {
        required: true,
        serializedName: "baseCalendarId",
        type: {
            name: "String"
        }
    }
};
export var baseCalendarIds = {
    parameterPath: [
        "options",
        "baseCalendarIds"
    ],
    mapper: {
        serializedName: "baseCalendarIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var buildingId0 = {
    parameterPath: "buildingId",
    mapper: {
        required: true,
        serializedName: "buildingId",
        type: {
            name: "Uuid"
        }
    }
};
export var buildingId1 = {
    parameterPath: "buildingId",
    mapper: {
        required: true,
        serializedName: "buildingId",
        type: {
            name: "String"
        }
    }
};
export var businessRuleName = {
    parameterPath: "businessRuleName",
    mapper: {
        required: true,
        serializedName: "businessRuleName",
        type: {
            name: "String"
        }
    }
};
export var businessRuleNames = {
    parameterPath: [
        "options",
        "businessRuleNames"
    ],
    mapper: {
        serializedName: "businessRuleNames",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var calendarId0 = {
    parameterPath: "calendarId",
    mapper: {
        required: true,
        serializedName: "calendarId",
        type: {
            name: "String"
        }
    }
};
export var calendarId1 = {
    parameterPath: "calendarId",
    mapper: {
        required: true,
        serializedName: "calendarId",
        type: {
            name: "Uuid"
        }
    }
};
export var calendarTypes = {
    parameterPath: [
        "options",
        "calendarTypes"
    ],
    mapper: {
        serializedName: "calendarTypes",
        type: {
            name: "String"
        }
    }
};
export var chargeId = {
    parameterPath: "chargeId",
    mapper: {
        required: true,
        serializedName: "chargeId",
        type: {
            name: "Uuid"
        }
    }
};
export var childrenLevel = {
    parameterPath: "childrenLevel",
    mapper: {
        required: true,
        serializedName: "childrenLevel",
        type: {
            name: "Number"
        }
    }
};
export var closedDayIds = {
    parameterPath: [
        "options",
        "closedDayIds"
    ],
    mapper: {
        serializedName: "closedDayIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var closingReasons = {
    parameterPath: [
        "options",
        "closingReasons"
    ],
    mapper: {
        serializedName: "closingReasons",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var code = {
    parameterPath: "code",
    mapper: {
        required: true,
        serializedName: "code",
        type: {
            name: "String"
        }
    }
};
export var codes0 = {
    parameterPath: "codes",
    mapper: {
        required: true,
        serializedName: "codes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var codes1 = {
    parameterPath: [
        "options",
        "codes"
    ],
    mapper: {
        serializedName: "codes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var culture = {
    parameterPath: "culture",
    mapper: {
        required: true,
        serializedName: "culture",
        type: {
            name: "String"
        }
    }
};
export var cultureCode = {
    parameterPath: "cultureCode",
    mapper: {
        required: true,
        serializedName: "cultureCode",
        type: {
            name: "String"
        }
    }
};
export var currentRole = {
    parameterPath: "currentRole",
    mapper: {
        required: true,
        serializedName: "currentRole",
        type: {
            name: "String"
        }
    }
};
export var currentVersion = {
    parameterPath: "currentVersion",
    mapper: {
        required: true,
        serializedName: "currentVersion",
        type: {
            name: "Number"
        }
    }
};
export var cycleId = {
    parameterPath: "cycleId",
    mapper: {
        required: true,
        serializedName: "cycleId",
        type: {
            name: "String"
        }
    }
};
export var cycleIds = {
    parameterPath: [
        "options",
        "cycleIds"
    ],
    mapper: {
        serializedName: "cycleIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var disputeDescription = {
    parameterPath: "disputeDescription",
    mapper: {
        required: true,
        serializedName: "disputeDescription",
        type: {
            name: "String"
        }
    }
};
export var documentId = {
    parameterPath: "documentId",
    mapper: {
        required: true,
        serializedName: "documentId",
        type: {
            name: "Uuid"
        }
    }
};
export var endDate = {
    parameterPath: [
        "options",
        "endDate"
    ],
    mapper: {
        serializedName: "endDate",
        type: {
            name: "DateTime"
        }
    }
};
export var entityId = {
    parameterPath: "entityId",
    mapper: {
        required: true,
        serializedName: "entityId",
        type: {
            name: "String"
        }
    }
};
export var entryId = {
    parameterPath: "entryId",
    mapper: {
        required: true,
        serializedName: "entryId",
        type: {
            name: "String"
        }
    }
};
export var eventId = {
    parameterPath: "eventId",
    mapper: {
        required: true,
        serializedName: "eventId",
        type: {
            name: "Uuid"
        }
    }
};
export var excludedProsecutingAuthorityIds = {
    parameterPath: [
        "options",
        "excludedProsecutingAuthorityIds"
    ],
    mapper: {
        serializedName: "excludedProsecutingAuthorityIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var excludedStatuses = {
    parameterPath: [
        "options",
        "excludedStatuses"
    ],
    mapper: {
        serializedName: "excludedStatuses",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var expiryDate = {
    parameterPath: "expiryDate",
    mapper: {
        required: true,
        serializedName: "expiryDate",
        type: {
            name: "DateTime"
        }
    }
};
export var fileId0 = {
    parameterPath: "fileId",
    mapper: {
        required: true,
        serializedName: "fileId",
        type: {
            name: "Uuid"
        }
    }
};
export var fileId1 = {
    parameterPath: "fileId",
    mapper: {
        required: true,
        serializedName: "fileId",
        type: {
            name: "String"
        }
    }
};
export var fileIds0 = {
    parameterPath: [
        "options",
        "fileIds"
    ],
    mapper: {
        serializedName: "fileIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var fileIds1 = {
    parameterPath: "fileIds",
    mapper: {
        required: true,
        serializedName: "fileIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var fileInvitationId = {
    parameterPath: "fileInvitationId",
    mapper: {
        required: true,
        serializedName: "fileInvitationId",
        type: {
            name: "Uuid"
        }
    }
};
export var fileStatus = {
    parameterPath: "fileStatus",
    mapper: {
        required: true,
        serializedName: "fileStatus",
        type: {
            name: "String"
        }
    }
};
export var formCode = {
    parameterPath: "formCode",
    mapper: {
        required: true,
        serializedName: "formCode",
        type: {
            name: "String"
        }
    }
};
export var formId = {
    parameterPath: "formId",
    mapper: {
        required: true,
        serializedName: "formId",
        type: {
            name: "String"
        }
    }
};
export var forumId = {
    parameterPath: "forumId",
    mapper: {
        required: true,
        serializedName: "forumId",
        type: {
            name: "Uuid"
        }
    }
};
export var hearingId = {
    parameterPath: "hearingId",
    mapper: {
        required: true,
        serializedName: "hearingId",
        type: {
            name: "Uuid"
        }
    }
};
export var id0 = {
    parameterPath: "id",
    mapper: {
        required: true,
        serializedName: "id",
        type: {
            name: "String"
        }
    }
};
export var id1 = {
    parameterPath: "id",
    mapper: {
        required: true,
        serializedName: "id",
        type: {
            name: "Uuid"
        }
    }
};
export var invitationId = {
    parameterPath: "invitationId",
    mapper: {
        required: true,
        serializedName: "invitationId",
        type: {
            name: "Uuid"
        }
    }
};
export var jEId = {
    parameterPath: "jEId",
    mapper: {
        required: true,
        serializedName: "JEId",
        type: {
            name: "String"
        }
    }
};
export var journalCodes = {
    parameterPath: "journalCodes",
    mapper: {
        required: true,
        serializedName: "journalCodes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var journalId = {
    parameterPath: "journalId",
    mapper: {
        required: true,
        serializedName: "journalId",
        type: {
            name: "Uuid"
        }
    }
};
export var judicialEntityId0 = {
    parameterPath: "judicialEntityId",
    mapper: {
        required: true,
        serializedName: "judicialEntityId",
        type: {
            name: "Uuid"
        }
    }
};
export var judicialEntityId1 = {
    parameterPath: "judicialEntityId",
    mapper: {
        required: true,
        serializedName: "judicialEntityId",
        type: {
            name: "String"
        }
    }
};
export var judicialEntityIds = {
    parameterPath: [
        "options",
        "judicialEntityIds"
    ],
    mapper: {
        serializedName: "judicialEntityIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var judicialFileId0 = {
    parameterPath: "judicialFileId",
    mapper: {
        required: true,
        serializedName: "judicialFileId",
        type: {
            name: "String"
        }
    }
};
export var judicialFileId1 = {
    parameterPath: "judicialFileId",
    mapper: {
        required: true,
        serializedName: "JudicialFileId",
        type: {
            name: "String"
        }
    }
};
export var judicialFileIds = {
    parameterPath: [
        "options",
        "judicialFileIds"
    ],
    mapper: {
        serializedName: "judicialFileIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var key = {
    parameterPath: "key",
    mapper: {
        required: true,
        serializedName: "key",
        type: {
            name: "Uuid"
        }
    }
};
export var labelId0 = {
    parameterPath: "labelId",
    mapper: {
        required: true,
        serializedName: "labelId",
        type: {
            name: "String"
        }
    }
};
export var labelId1 = {
    parameterPath: "labelId",
    mapper: {
        required: true,
        serializedName: "labelId",
        type: {
            name: "Uuid"
        }
    }
};
export var labelSection = {
    parameterPath: "labelSection",
    mapper: {
        required: true,
        serializedName: "labelSection",
        type: {
            name: "String"
        }
    }
};
export var lang = {
    parameterPath: "lang",
    mapper: {
        required: true,
        serializedName: "lang",
        type: {
            name: "String"
        }
    }
};
export var lastModified0 = {
    parameterPath: "lastModified",
    mapper: {
        required: true,
        serializedName: "lastModified",
        type: {
            name: "String"
        }
    }
};
export var lastModified1 = {
    parameterPath: "lastModified",
    mapper: {
        required: true,
        serializedName: "lastModified",
        type: {
            name: "DateTime"
        }
    }
};
export var lastModifiedDate = {
    parameterPath: "lastModifiedDate",
    mapper: {
        required: true,
        serializedName: "lastModifiedDate",
        type: {
            name: "String"
        }
    }
};
export var linkId = {
    parameterPath: "linkId",
    mapper: {
        required: true,
        serializedName: "linkId",
        type: {
            name: "String"
        }
    }
};
export var locationBuildingIds = {
    parameterPath: [
        "options",
        "locationBuildingIds"
    ],
    mapper: {
        serializedName: "locationBuildingIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var locationRoomId = {
    parameterPath: "locationRoomId",
    mapper: {
        required: true,
        serializedName: "locationRoomId",
        type: {
            name: "String"
        }
    }
};
export var locationRoomIds = {
    parameterPath: [
        "options",
        "locationRoomIds"
    ],
    mapper: {
        serializedName: "locationRoomIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var maxCreatedDate = {
    parameterPath: [
        "options",
        "maxCreatedDate"
    ],
    mapper: {
        serializedName: "maxCreatedDate",
        type: {
            name: "DateTime"
        }
    }
};
export var menuId = {
    parameterPath: "menuId",
    mapper: {
        required: true,
        serializedName: "menuId",
        type: {
            name: "Uuid"
        }
    }
};
export var minCreatedDate = {
    parameterPath: [
        "options",
        "minCreatedDate"
    ],
    mapper: {
        serializedName: "minCreatedDate",
        type: {
            name: "DateTime"
        }
    }
};
export var modifiedTicks = {
    parameterPath: "modifiedTicks",
    mapper: {
        required: true,
        serializedName: "modifiedTicks",
        type: {
            name: "String"
        }
    }
};
export var name = {
    parameterPath: "name",
    mapper: {
        required: true,
        serializedName: "name",
        type: {
            name: "String"
        }
    }
};
export var names0 = {
    parameterPath: [
        "options",
        "names"
    ],
    mapper: {
        serializedName: "names",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var names1 = {
    parameterPath: "names",
    mapper: {
        required: true,
        serializedName: "names",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var notificationCode0 = {
    parameterPath: "notificationCode",
    mapper: {
        required: true,
        serializedName: "notificationCode",
        type: {
            name: "String"
        }
    }
};
export var notificationCode1 = {
    parameterPath: [
        "options",
        "notificationCode"
    ],
    mapper: {
        serializedName: "notificationCode",
        type: {
            name: "String"
        }
    }
};
export var notificationId = {
    parameterPath: "notificationId",
    mapper: {
        required: true,
        serializedName: "notificationId",
        type: {
            name: "Number"
        }
    }
};
export var objectCode = {
    parameterPath: "objectCode",
    mapper: {
        required: true,
        serializedName: "objectCode",
        type: {
            name: "String"
        }
    }
};
export var orderBy = {
    parameterPath: [
        "options",
        "orderBy"
    ],
    mapper: {
        serializedName: "orderBy",
        type: {
            name: "String"
        }
    }
};
export var orderByDescending = {
    parameterPath: [
        "options",
        "orderByDescending"
    ],
    mapper: {
        serializedName: "orderByDescending",
        type: {
            name: "Boolean"
        }
    }
};
export var partyEntityCodes = {
    parameterPath: [
        "options",
        "partyEntityCodes"
    ],
    mapper: {
        serializedName: "partyEntityCodes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var partyEntityIds = {
    parameterPath: [
        "options",
        "partyEntityIds"
    ],
    mapper: {
        serializedName: "partyEntityIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var partyId0 = {
    parameterPath: "partyId",
    mapper: {
        required: true,
        serializedName: "partyId",
        type: {
            name: "String"
        }
    }
};
export var partyId1 = {
    parameterPath: "partyId",
    mapper: {
        required: true,
        serializedName: "partyId",
        type: {
            name: "Uuid"
        }
    }
};
export var partyInvitationId = {
    parameterPath: "partyInvitationId",
    mapper: {
        required: true,
        serializedName: "partyInvitationId",
        type: {
            name: "Uuid"
        }
    }
};
export var partyType = {
    parameterPath: "partyType",
    mapper: {
        required: true,
        serializedName: "partyType",
        type: {
            name: "String"
        }
    }
};
export var periodAvailabilityGroupId = {
    parameterPath: "periodAvailabilityGroupId",
    mapper: {
        required: true,
        serializedName: "periodAvailabilityGroupId",
        type: {
            name: "String"
        }
    }
};
export var periodAvailabilityId = {
    parameterPath: "periodAvailabilityId",
    mapper: {
        required: true,
        serializedName: "periodAvailabilityId",
        type: {
            name: "String"
        }
    }
};
export var periodAvailabilityIds = {
    parameterPath: [
        "options",
        "periodAvailabilityIds"
    ],
    mapper: {
        serializedName: "periodAvailabilityIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var prosecutingAuthorityIds = {
    parameterPath: [
        "options",
        "prosecutingAuthorityIds"
    ],
    mapper: {
        serializedName: "prosecutingAuthorityIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var prosecutingAuthorityNames = {
    parameterPath: [
        "options",
        "prosecutingAuthorityNames"
    ],
    mapper: {
        serializedName: "prosecutingAuthorityNames",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var realm = {
    parameterPath: "realm",
    mapper: {
        required: true,
        serializedName: "realm",
        type: {
            name: "String"
        }
    }
};
export var representativeId = {
    parameterPath: "representativeId",
    mapper: {
        required: true,
        serializedName: "representativeId",
        type: {
            name: "Uuid"
        }
    }
};
export var representativeIds = {
    parameterPath: [
        "options",
        "representativeIds"
    ],
    mapper: {
        serializedName: "representativeIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var requestId = {
    parameterPath: "requestId",
    mapper: {
        required: true,
        serializedName: "requestId",
        type: {
            name: "Uuid"
        }
    }
};
export var resourceTypes = {
    parameterPath: [
        "options",
        "resourceTypes"
    ],
    mapper: {
        serializedName: "resourceTypes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var roleCode = {
    parameterPath: "roleCode",
    mapper: {
        required: true,
        serializedName: "roleCode",
        type: {
            name: "String"
        }
    }
};
export var roomId0 = {
    parameterPath: "roomId",
    mapper: {
        required: true,
        serializedName: "roomId",
        type: {
            name: "Uuid"
        }
    }
};
export var roomId1 = {
    parameterPath: "roomId",
    mapper: {
        required: true,
        serializedName: "roomId",
        type: {
            name: "String"
        }
    }
};
export var roomIds = {
    parameterPath: [
        "options",
        "roomIds"
    ],
    mapper: {
        serializedName: "roomIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var scheduleEntryId = {
    parameterPath: "scheduleEntryId",
    mapper: {
        required: true,
        serializedName: "scheduleEntryId",
        type: {
            name: "String"
        }
    }
};
export var schedulePatternId = {
    parameterPath: "schedulePatternId",
    mapper: {
        required: true,
        serializedName: "schedulePatternId",
        type: {
            name: "String"
        }
    }
};
export var schedulePatternIds = {
    parameterPath: [
        "options",
        "schedulePatternIds"
    ],
    mapper: {
        serializedName: "schedulePatternIds",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "Uuid"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var searchBy = {
    parameterPath: [
        "options",
        "searchBy"
    ],
    mapper: {
        serializedName: "searchBy",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var searchStatuses = {
    parameterPath: [
        "options",
        "searchStatuses"
    ],
    mapper: {
        serializedName: "searchStatuses",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var searchText = {
    parameterPath: [
        "options",
        "searchText"
    ],
    mapper: {
        serializedName: "searchText",
        type: {
            name: "String"
        }
    }
};
export var skip = {
    parameterPath: [
        "options",
        "skip"
    ],
    mapper: {
        serializedName: "skip",
        type: {
            name: "Number"
        }
    }
};
export var startDate = {
    parameterPath: [
        "options",
        "startDate"
    ],
    mapper: {
        serializedName: "startDate",
        type: {
            name: "DateTime"
        }
    }
};
export var status = {
    parameterPath: "status",
    mapper: {
        required: true,
        serializedName: "status",
        type: {
            name: "String"
        }
    }
};
export var statuses = {
    parameterPath: [
        "options",
        "statuses"
    ],
    mapper: {
        serializedName: "statuses",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var statusFrom = {
    parameterPath: "statusFrom",
    mapper: {
        required: true,
        serializedName: "statusFrom",
        type: {
            name: "String"
        }
    }
};
export var statusTo = {
    parameterPath: "statusTo",
    mapper: {
        required: true,
        serializedName: "statusTo",
        type: {
            name: "String"
        }
    }
};
export var tagCode = {
    parameterPath: "tagCode",
    mapper: {
        required: true,
        serializedName: "tagCode",
        type: {
            name: "String"
        }
    }
};
export var tagCodes = {
    parameterPath: [
        "options",
        "tagCodes"
    ],
    mapper: {
        serializedName: "tagCodes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var tagId = {
    parameterPath: "tagId",
    mapper: {
        required: true,
        serializedName: "tagId",
        type: {
            name: "Uuid"
        }
    }
};
export var take0 = {
    parameterPath: [
        "options",
        "take"
    ],
    mapper: {
        serializedName: "take",
        type: {
            name: "Number"
        }
    }
};
export var take1 = {
    parameterPath: "take",
    mapper: {
        required: true,
        serializedName: "take",
        type: {
            name: "Number"
        }
    }
};
export var timeEventId = {
    parameterPath: "timeEventId",
    mapper: {
        required: true,
        serializedName: "timeEventId",
        type: {
            name: "Uuid"
        }
    }
};
export var timerDate = {
    parameterPath: "timerDate",
    mapper: {
        required: true,
        serializedName: "timerDate",
        type: {
            name: "DateTime"
        }
    }
};
export var timerStatus = {
    parameterPath: "timerStatus",
    mapper: {
        required: true,
        serializedName: "timerStatus",
        type: {
            name: "String"
        }
    }
};
export var titles = {
    parameterPath: [
        "options",
        "titles"
    ],
    mapper: {
        serializedName: "titles",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var type = {
    parameterPath: "type",
    mapper: {
        required: true,
        serializedName: "type",
        type: {
            name: "String"
        }
    }
};
export var urn = {
    parameterPath: "urn",
    mapper: {
        required: true,
        serializedName: "urn",
        type: {
            name: "String"
        }
    }
};
export var userCodes = {
    parameterPath: [
        "options",
        "userCodes"
    ],
    mapper: {
        serializedName: "userCodes",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var userId = {
    parameterPath: "userId",
    mapper: {
        required: true,
        serializedName: "userId",
        type: {
            name: "String"
        }
    }
};
export var username = {
    parameterPath: "username",
    mapper: {
        required: true,
        serializedName: "username",
        type: {
            name: "String"
        }
    }
};
export var userRoles = {
    parameterPath: [
        "options",
        "userRoles"
    ],
    mapper: {
        serializedName: "userRoles",
        type: {
            name: "Sequence",
            element: {
                type: {
                    name: "String"
                }
            }
        }
    },
    collectionFormat: msRest.QueryCollectionFormat.Multi
};
export var weekday = {
    parameterPath: "weekday",
    mapper: {
        required: true,
        serializedName: "weekday",
        type: {
            name: "String"
        }
    }
};
export var witnessCode = {
    parameterPath: "witnessCode",
    mapper: {
        required: true,
        serializedName: "witnessCode",
        type: {
            name: "String"
        }
    }
};
export var witnessId = {
    parameterPath: "witnessId",
    mapper: {
        required: true,
        serializedName: "witnessId",
        type: {
            name: "Uuid"
        }
    }
};
//# sourceMappingURL=parameters.js.map