/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export { CyberjusticeLabKernelSharedTagLocalizedLabelData, CyberjusticeLabKernelSharedTagTagLinkData, CyberjusticeLabKernelSharedTagTagData, CyberjusticeLabKernelSharedTagLabelData, CyberjusticeLabKernelSharedTagLabelLocalizationData, CyberjusticeLabKernelSharedTagTagLinkUpdateData, CyberjusticeLabKernelSharedTagLabelUpdateData, CyberjusticeLabKernelSharedTagLabelLocalizationBaseData, CyberjusticeLabKernelSharedTagTagLinkCreateData, CyberjusticeLabKernelSharedTagLabelCreateData } from "../models/mappers";
//# sourceMappingURL=tagMappers.js.map