/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/judicialEntityMappers";
import * as Parameters from "../models/parameters";
import { CyberjusticeAPIsContext } from "../cyberjusticeAPIsContext";

/** Class representing a JudicialEntity. */
export class JudicialEntity {
  private readonly client: CyberjusticeAPIsContext;

  /**
   * Create a JudicialEntity.
   * @param {CyberjusticeAPIsContext} client Reference to the service client.
   */
  constructor(client: CyberjusticeAPIsContext) {
    this.client = client;
  }

  /**
   * @summary Return the judicial entity configuration.
   * @param jEId ID of the judicial entity.
   * @param [options] The optional parameters
   * @returns Promise<Models.JudicialEntityGetJudicialEntityCompleteInfosResponse>
   */
  getJudicialEntityCompleteInfos(jEId: string, options?: msRest.RequestOptionsBase): Promise<Models.JudicialEntityGetJudicialEntityCompleteInfosResponse>;
  /**
   * @param jEId ID of the judicial entity.
   * @param callback The callback
   */
  getJudicialEntityCompleteInfos(jEId: string, callback: msRest.ServiceCallback<Models.CyberjusticeLabKernelServiceContractsJudicialEntityJudicialEntityData>): void;
  /**
   * @param jEId ID of the judicial entity.
   * @param options The optional parameters
   * @param callback The callback
   */
  getJudicialEntityCompleteInfos(jEId: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.CyberjusticeLabKernelServiceContractsJudicialEntityJudicialEntityData>): void;
  getJudicialEntityCompleteInfos(jEId: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.CyberjusticeLabKernelServiceContractsJudicialEntityJudicialEntityData>, callback?: msRest.ServiceCallback<Models.CyberjusticeLabKernelServiceContractsJudicialEntityJudicialEntityData>): Promise<Models.JudicialEntityGetJudicialEntityCompleteInfosResponse> {
    return this.client.sendOperationRequest(
      {
        jEId,
        options
      },
      getJudicialEntityCompleteInfosOperationSpec,
      callback) as Promise<Models.JudicialEntityGetJudicialEntityCompleteInfosResponse>;
  }

  /**
   * @summary Return the judicial entity ID.
   * @param urn URN of the judicial entity.
   * @param [options] The optional parameters
   * @returns Promise<Models.JudicialEntityGetJudicialEntityResponse>
   */
  getJudicialEntity(urn: string, options?: msRest.RequestOptionsBase): Promise<Models.JudicialEntityGetJudicialEntityResponse>;
  /**
   * @param urn URN of the judicial entity.
   * @param callback The callback
   */
  getJudicialEntity(urn: string, callback: msRest.ServiceCallback<string>): void;
  /**
   * @param urn URN of the judicial entity.
   * @param options The optional parameters
   * @param callback The callback
   */
  getJudicialEntity(urn: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<string>): void;
  getJudicialEntity(urn: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<string>, callback?: msRest.ServiceCallback<string>): Promise<Models.JudicialEntityGetJudicialEntityResponse> {
    return this.client.sendOperationRequest(
      {
        urn,
        options
      },
      getJudicialEntityOperationSpec,
      callback) as Promise<Models.JudicialEntityGetJudicialEntityResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getJudicialEntityCompleteInfosOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "JudicialEntity/GET/JudicialEntityCompleteInfos",
  queryParameters: [
    Parameters.jEId
  ],
  responses: {
    200: {
      bodyMapper: Mappers.CyberjusticeLabKernelServiceContractsJudicialEntityJudicialEntityData
    },
    default: {}
  },
  serializer
};

const getJudicialEntityOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "JudicialEntity/GET/JudicialEntityId",
  queryParameters: [
    Parameters.urn
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Uuid"
        }
      }
    },
    default: {}
  },
  serializer
};
