/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as tslib_1 from "tslib";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { CyberjusticeAPIsContext } from "./cyberjusticeAPIsContext";
var CyberjusticeAPIs = /** @class */ (function (_super) {
    tslib_1.__extends(CyberjusticeAPIs, _super);
    /**
     * Initializes a new instance of the CyberjusticeAPIs class.
     * @param [options] The parameter options
     */
    function CyberjusticeAPIs(options) {
        var _this = _super.call(this, options) || this;
        _this.async = new operations.Async(_this);
        _this.businessInformation = new operations.BusinessInformation(_this);
        _this.calendar = new operations.Calendar(_this);
        _this.document = new operations.Document(_this);
        _this.exchange = new operations.Exchange(_this);
        _this.form = new operations.Form(_this);
        _this.hearing = new operations.Hearing(_this);
        _this.journal = new operations.Journal(_this);
        _this.judicialEntity = new operations.JudicialEntity(_this);
        _this.judicialFile = new operations.JudicialFile(_this);
        _this.location = new operations.Location(_this);
        _this.lookup = new operations.Lookup(_this);
        _this.prosecutingAuthority = new operations.ProsecutingAuthority(_this);
        _this.request = new operations.Request(_this);
        _this.secureMail = new operations.SecureMail(_this);
        _this.security = new operations.Security(_this);
        _this.tag = new operations.Tag(_this);
        _this.uProfile = new operations.UProfile(_this);
        _this.user = new operations.User(_this);
        _this.witness = new operations.Witness(_this);
        return _this;
    }
    return CyberjusticeAPIs;
}(CyberjusticeAPIsContext));
// Operation Specifications
export { CyberjusticeAPIs, CyberjusticeAPIsContext, Models as CyberjusticeAPIsModels, Mappers as CyberjusticeAPIsMappers };
export * from "./operations";
//# sourceMappingURL=cyberjusticeAPIs.js.map